variable = 6 * (1 - 2)
print (variable)

var1 = ("all")
var2 = ("work")
var3 = ("and")
var4 = ("no")
var5 = ("play")
var6 = ("makes")
var7 = ("malik")
var8 = ("a")
var9 = ("dull")
var10 = ("man")
print(var1,var2, var3, var5, var6, var7, var8, var9, var10)